.TH "sl::Bitmap" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Bitmap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <draw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 0"
.br
.ti -1c
.RI "int \fBheight\fP = 0"
.br
.ti -1c
.RI "std::vector< Uint8 > \fBpixels\fP"
.br
.ti -1c
.RI "std::uint32_t \fBgpu_texture\fP = 0"
.br
.ti -1c
.RI "std::uint32_t \fBfbo\fP = 0"
.br
.ti -1c
.RI "bool \fBram_dirty\fP = false"
.br
.ti -1c
.RI "bool \fBgpu_dirty\fP = false"
.br
.ti -1c
.RI "BitmapKind \fBkind\fP = BitmapKind::Bitmap"
.br
.in -1c
.SH "Detailed Description"
.PP 
A bitmap may retain pixels in RAM, on the GPU, or both\&. Pixel data is RGBA8\&. The pixel origin and all primitive coordinates are in the top-left corner\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::uint32_t sl::Bitmap::fbo = 0"
Non-zero if this bitmap is an offscreen render target (see create_render_target())\&. 
.SS "bool sl::Bitmap::gpu_dirty = false"
True when the GPU texture contains changes not yet downloaded to RAM\&. 
.SS "std::uint32_t sl::Bitmap::gpu_texture = 0"
Backend texture handle; zero when no GPU texture exists\&. 
.SS "int sl::Bitmap::height = 0"
\fBBitmap\fP height in pixels\&. 
.SS "BitmapKind sl::Bitmap::kind = BitmapKind::Bitmap"
Distinguishes ordinary bitmaps from the display framebuffer\&. 
.SS "std::vector<Uint8> sl::Bitmap::pixels"
CPU-side RGBA8 pixels, when retained or acquired\&. 
.SS "bool sl::Bitmap::ram_dirty = false"
True when CPU pixels contain changes not yet uploaded to the GPU\&. 
.SS "int sl::Bitmap::width = 0"
\fBBitmap\fP width in pixels\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
