.TH "sl::Camera" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scene3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "glm::mat4 \fBview_matrix\fP () const"
.br
.ti -1c
.RI "glm::mat4 \fBprojection_matrix\fP (float aspect_ratio) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP {0\&.0f, 0\&.0f, 3\&.0f}"
.br
.ti -1c
.RI "glm::vec3 \fBtarget\fP {0\&.0f, 0\&.0f, 0\&.0f}"
.br
.ti -1c
.RI "glm::vec3 \fBup\fP {0\&.0f, 1\&.0f, 0\&.0f}"
.br
.ti -1c
.RI "float \fBfield_of_view\fP = 60\&.0f"
.br
.ti -1c
.RI "float \fBnear_plane\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBfar_plane\fP = 1000\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
A perspective camera using right-handed GLM coordinates\&. 
.SH "Member Function Documentation"
.PP 
.SS "glm::mat4 sl::Camera::projection_matrix (float aspect_ratio) const\fC [inline]\fP"
Build a perspective projection matrix\&. 
.SS "glm::mat4 sl::Camera::view_matrix () const\fC [inline]\fP"
Build the camera view matrix\&. 
.SH "Member Data Documentation"
.PP 
.SS "float sl::Camera::far_plane = 1000\&.0f"
Far clipping distance\&. 
.SS "float sl::Camera::field_of_view = 60\&.0f"
Vertical field of view in degrees\&. 
.SS "float sl::Camera::near_plane = 0\&.1f"
Near clipping distance\&. 
.SS "glm::vec3 sl::Camera::position {0\&.0f, 0\&.0f, 3\&.0f}"
\fBCamera\fP position in right-handed world coordinates\&. 
.SS "glm::vec3 sl::Camera::target {0\&.0f, 0\&.0f, 0\&.0f}"
Point the camera looks toward\&. 
.SS "glm::vec3 sl::Camera::up {0\&.0f, 1\&.0f, 0\&.0f}"
\fBCamera\fP's upward direction\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
