.TH "sl::Colour" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Colour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <draw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBred\fP"
.br
.ti -1c
.RI "Uint8 \fBgreen\fP"
.br
.ti -1c
.RI "Uint8 \fBblue\fP"
.br
.ti -1c
.RI "Uint8 \fBalpha\fP = 255"
.br
.in -1c
.SH "Detailed Description"
.PP 
An RGBA colour with 8-bit channels\&. 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 sl::Colour::alpha = 255"
Alpha channel, in the range 0-255; defaults to opaque\&. 
.SS "Uint8 sl::Colour::blue"
Blue channel, in the range 0-255\&. 
.SS "Uint8 sl::Colour::green"
Green channel, in the range 0-255\&. 
.SS "Uint8 sl::Colour::red"
Red channel, in the range 0-255\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
