.TH "sl::ChromaticAberration" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::ChromaticAberration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_strength\fP (float strength)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, int x=0, int y=0, int width=0, int height=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Separates RGB samples toward the screen edges for a lens/damage effect\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::ChromaticAberration::apply (\fBBitmap\fP * source, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP) const"
Apply the effect to a bitmap region\&. 
.SS "const std::string & sl::ChromaticAberration::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::ChromaticAberration::initialise ()"
Compile the chromatic-aberration shader and prepare the effect\&. 
.SS "bool sl::ChromaticAberration::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "void sl::ChromaticAberration::set_strength (float strength)"
Set the normalized separation between colour channels\&. 
.SS "void sl::ChromaticAberration::shutdown ()"
Release resources owned by the effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
