.TH "sl::FluidSimulation" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::FluidSimulation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fluid\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 0"
.br
.ti -1c
.RI "int \fBheight\fP = 0"
.br
.ti -1c
.RI "std::vector< \fBFluidCell\fP > \fBcells\fP"
.br
.ti -1c
.RI "std::uint32_t \fBturn\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fixed-size cellular-automata grid and its simulation tick\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBFluidCell\fP> sl::FluidSimulation::cells"
Cells in row-major order, indexed as y * width + x\&. 
.SS "int sl::FluidSimulation::height = 0"
Grid height in cells\&. 
.SS "std::uint32_t sl::FluidSimulation::turn = 0"
Number of completed simulation steps\&. 
.SS "int sl::FluidSimulation::width = 0"
Grid width in cells\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
