.TH "sl::FluidCell" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::FluidCell
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fluid\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FluidElement \fBtype\fP = FluidElement::empty"
.br
.ti -1c
.RI "float \fBmass\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBtemp\fP = 20\&.0f"
.br
.ti -1c
.RI "std::uint8_t \fBlife\fP = 0"
.br
.ti -1c
.RI "std::int8_t \fBvariation\fP = 0"
.br
.ti -1c
.RI "std::uint32_t \fBturn\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Material and per-cell state stored at one grid coordinate\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::uint8_t sl::FluidCell::life = 0"
Remaining lifetime for transient elements such as fire or smoke\&. 
.SS "float sl::FluidCell::mass = 0\&.0f"
Material mass used by movement and pressure calculations\&. 
.SS "float sl::FluidCell::temp = 20\&.0f"
Cell temperature in degrees Celsius\&. 
.SS "std::uint32_t sl::FluidCell::turn = 0"
Tick on which this cell was last processed\&. 
.SS "FluidElement sl::FluidCell::type = FluidElement::empty"
Material occupying this cell\&. 
.SS "std::int8_t sl::FluidCell::variation = 0"
Small per-cell visual or simulation variation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
