.TH "sl::HeatHaze" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::HeatHaze
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_strength\fP (float strength)"
.br
.ti -1c
.RI "void \fBset_frequency\fP (float frequency)"
.br
.ti -1c
.RI "void \fBset_time\fP (float time)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, int x=0, int y=0, int width=0, int height=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Applies animated sinusoidal UV distortion for heat, water, or portal effects\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::HeatHaze::apply (\fBBitmap\fP * source, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP) const"
Apply the current heat-haze distortion to a bitmap region\&. 
.SS "const std::string & sl::HeatHaze::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::HeatHaze::initialise ()"
Compile the heat-haze shader and prepare the effect\&. 
.SS "bool sl::HeatHaze::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "void sl::HeatHaze::set_frequency (float frequency)"
Set the spatial frequency of the distortion pattern\&. 
.SS "void sl::HeatHaze::set_strength (float strength)"
Set the maximum texture-coordinate displacement\&. 
.SS "void sl::HeatHaze::set_time (float time)"
Set animation time in seconds\&. 
.SS "void sl::HeatHaze::shutdown ()"
Release resources owned by the effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
