.TH "sl::IsoGridPoint" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::IsoGridPoint \- Discrete grid cell coordinates in isometric tilemap space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isometric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP = 0"
.br
.ti -1c
.RI "int \fBy\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Discrete grid cell coordinates in isometric tilemap space\&. 
.SH "Member Data Documentation"
.PP 
.SS "int sl::IsoGridPoint::x = 0"
Tile column\&. 
.SS "int sl::IsoGridPoint::y = 0"
Tile row\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
