.TH "sl::IsoBounds" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::IsoBounds \- Axis-aligned tile coordinate bounding box in isometric grid space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isometric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmin_x\fP = 0"
.br
.ti -1c
.RI "int \fBmin_y\fP = 0"
.br
.ti -1c
.RI "int \fBmax_x\fP = 0"
.br
.ti -1c
.RI "int \fBmax_y\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Axis-aligned tile coordinate bounding box in isometric grid space\&. 
.SH "Member Data Documentation"
.PP 
.SS "int sl::IsoBounds::max_x = 0"
Maximum tile column, inclusive\&. 
.SS "int sl::IsoBounds::max_y = 0"
Maximum tile row, inclusive\&. 
.SS "int sl::IsoBounds::min_x = 0"
Minimum tile column, inclusive\&. 
.SS "int sl::IsoBounds::min_y = 0"
Minimum tile row, inclusive\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
