.TH "sl::IsoTileDiamond" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::IsoTileDiamond \- The four vertices of an isometric tile diamond in screen space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isometric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIsoPoint\fP \fBtop\fP"
.br
.ti -1c
.RI "\fBIsoPoint\fP \fBright\fP"
.br
.ti -1c
.RI "\fBIsoPoint\fP \fBbottom\fP"
.br
.ti -1c
.RI "\fBIsoPoint\fP \fBleft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The four vertices of an isometric tile diamond in screen space\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBIsoPoint\fP sl::IsoTileDiamond::bottom"
Bottom vertex in screen coordinates\&. 
.SS "\fBIsoPoint\fP sl::IsoTileDiamond::left"
Left vertex in screen coordinates\&. 
.SS "\fBIsoPoint\fP sl::IsoTileDiamond::right"
Right vertex in screen coordinates\&. 
.SS "\fBIsoPoint\fP sl::IsoTileDiamond::top"
Top vertex in screen coordinates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
