.TH "sl::IsoPoint" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::IsoPoint \- 2D point representing screen or continuous world coordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isometric\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBy\fP = 0\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
2D point representing screen or continuous world coordinates\&. 
.SH "Member Data Documentation"
.PP 
.SS "float sl::IsoPoint::x = 0\&.0f"
Horizontal coordinate\&. 
.SS "float sl::IsoPoint::y = 0\&.0f"
Vertical coordinate\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
