.TH "sl::LightingPass" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::LightingPass
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLightingPass\fP (const \fBLightingPass\fP &)=delete"
.br
.ti -1c
.RI "\fBLightingPass\fP & \fBoperator=\fP (const \fBLightingPass\fP &)=delete"
.br
.ti -1c
.RI "\fBLightingPass\fP (\fBLightingPass\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBLightingPass\fP & \fBoperator=\fP (\fBLightingPass\fP &&other) noexcept"
.br
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_ambient\fP (float ambient)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, const \fBLight\fP &light, int x=0, int y=0, int width=0, int height=0, const std::vector< \fBShadowCaster\fP > &casters={}) const"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, const std::vector< \fBLight\fP > &lights, int x=0, int y=0, int width=0, int height=0, const std::vector< \fBShadowCaster\fP > &casters={}) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBmax_shadow_lights\fP = 8"
.br
.ti -1c
.RI "static constexpr int \fBtile_size\fP = 16"
.br
.ti -1c
.RI "static constexpr int \fBmax_lights_per_tile\fP = 128"
.br
.in -1c
.SH "Detailed Description"
.PP 
Modulates a rendered scene with an arbitrary number of radial lights\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sl::LightingPass::LightingPass (\fBLightingPass\fP && other)\fC [noexcept]\fP"
Transfer ownership of lighting shaders and GPU buffers\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::LightingPass::apply (\fBBitmap\fP * source, const \fBLight\fP & light, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP, const std::vector< \fBShadowCaster\fP > & casters = \fC{}\fP) const"
Apply ambient plus radial lighting and polygon shadows to a bitmap\&. 
.SS "void sl::LightingPass::apply (\fBBitmap\fP * source, const std::vector< \fBLight\fP > & lights, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP, const std::vector< \fBShadowCaster\fP > & casters = \fC{}\fP) const"
Apply an arbitrary batch of lights; only the first max_shadow_lights receive shadows\&. 
.SS "const std::string & sl::LightingPass::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::LightingPass::initialise ()"
Compile the lighting shader and prepare the effect\&. 
.SS "bool sl::LightingPass::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "\fBLightingPass\fP & sl::LightingPass::operator= (\fBLightingPass\fP && other)\fC [noexcept]\fP"
Release this pass's resources and take ownership of another pass's\&. 
.SS "void sl::LightingPass::set_ambient (float ambient)"
Set the minimum scene illumination, from 0 (black) to 1 (full brightness)\&. 
.SS "void sl::LightingPass::shutdown ()"
Release resources owned by the effect\&. 
.SH "Member Data Documentation"
.PP 
.SS "constexpr int sl::LightingPass::max_lights_per_tile = 128\fC [static]\fP, \fC [constexpr]\fP"
Maximum lights stored for one screen tile\&. 
.SS "constexpr std::size_t sl::LightingPass::max_shadow_lights = 8\fC [static]\fP, \fC [constexpr]\fP"
Maximum number of lights processed with shadow casters\&. 
.SS "constexpr int sl::LightingPass::tile_size = 16\fC [static]\fP, \fC [constexpr]\fP"
Screen tile dimension used to cull lights\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
