.TH "sl::PointVertex" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::PointVertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <draw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBy\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBColour\fP \fBcolour\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One screen-space point for draw_points(), e\&.g\&. a GPU-simulated particle\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBColour\fP sl::PointVertex::colour"
Point colour\&. 
.SS "float sl::PointVertex::x = 0\&.0f"
Horizontal screen coordinate in pixels\&. 
.SS "float sl::PointVertex::y = 0\&.0f"
Vertical screen coordinate in pixels\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
