.TH "sl::PixelPallete" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::PixelPallete
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload\fP (const std::string &filename)"
.br
.ti -1c
.RI "const \fBColour\fP \fBat\fP (std::size_t index) const"
.br
.ti -1c
.RI "\fBColour\fP & \fBoperator[]\fP (std::size_t index)"
.br
.ti -1c
.RI "const size_t \fBsize\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A collection of colours loaded from the first row of an image\&. 
.SH "Member Function Documentation"
.PP 
.SS "const \fBColour\fP sl::PixelPallete::at (std::size_t index) const\fC [inline]\fP"
Return a palette colour by index, throwing std::out_of_range if invalid\&. 
.SS "bool sl::PixelPallete::load (const std::string & filename)\fC [inline]\fP"
Load and append the first image row's pixels as palette entries\&. 
.SS "\fBColour\fP & sl::PixelPallete::operator[] (std::size_t index)\fC [inline]\fP"
Return a mutable palette colour by index, throwing std::out_of_range if invalid\&. 
.SS "const size_t sl::PixelPallete::size () const\fC [inline]\fP"
Return the number of stored colours\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
