.TH "sl::Pixelate" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Pixelate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_pixel_size\fP (float size)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, int x=0, int y=0, int width=0, int height=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reduces a bitmap to configurable screen-space colour blocks\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::Pixelate::apply (\fBBitmap\fP * source, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP) const"
Apply pixelation to a bitmap region\&. 
.SS "const std::string & sl::Pixelate::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::Pixelate::initialise ()"
Compile the pixelation shader and prepare the effect\&. 
.SS "bool sl::Pixelate::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "void sl::Pixelate::set_pixel_size (float size)"
Set the pixel-block size in source pixels\&. 
.SS "void sl::Pixelate::shutdown ()"
Release resources owned by the effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
