.TH "sl::RadialBlur" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::RadialBlur
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_centre\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBset_strength\fP (float strength)"
.br
.ti -1c
.RI "void \fBset_samples\fP (int samples)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, int x=0, int y=0, int width=0, int height=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Blurs pixels along rays from a configurable focal point\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::RadialBlur::apply (\fBBitmap\fP * source, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP) const"
Apply the radial blur to a bitmap region\&. 
.SS "const std::string & sl::RadialBlur::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::RadialBlur::initialise ()"
Compile the radial-blur shader and prepare the effect\&. 
.SS "bool sl::RadialBlur::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "void sl::RadialBlur::set_centre (float x, float y)"
Set the focal point in normalized source coordinates from 0 to 1\&. 
.SS "void sl::RadialBlur::set_samples (int samples)"
Set the number of samples used for the blur\&. 
.SS "void sl::RadialBlur::set_strength (float strength)"
Set the distance samples are displaced toward the focal point\&. 
.SS "void sl::RadialBlur::shutdown ()"
Release resources owned by the effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
