.TH "sl::ScreenShake" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::ScreenShake
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenShake\fP (const \fBScreenShake\fP &)=delete"
.br
.ti -1c
.RI "\fBScreenShake\fP & \fBoperator=\fP (const \fBScreenShake\fP &)=delete"
.br
.ti -1c
.RI "void \fBtrigger\fP (float amplitude, float duration)"
.br
.ti -1c
.RI "void \fBupdate\fP (float delta_seconds)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBactive\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Applies a decaying camera offset to 2D projections for impact and motion effects\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool sl::ScreenShake::active () const"
Return whether the shake still has non-zero duration\&. 
.SS "void sl::ScreenShake::clear ()"
Stop shaking and reset the current offset\&. 
.SS "void sl::ScreenShake::trigger (float amplitude, float duration)"
Start a shake with pixel amplitude and duration in seconds\&. 
.SS "void sl::ScreenShake::update (float delta_seconds)"
Advance the shake envelope by elapsed seconds\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
