.TH "sl::Shockwave" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Shockwave
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise\fP ()"
.br
.ti -1c
.RI "void \fBshutdown\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "const std::string & \fBerror\fP () const"
.br
.ti -1c
.RI "void \fBset_centre\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBset_radius\fP (float radius)"
.br
.ti -1c
.RI "void \fBset_width\fP (float width)"
.br
.ti -1c
.RI "void \fBset_strength\fP (float strength)"
.br
.ti -1c
.RI "void \fBapply\fP (\fBBitmap\fP *source, int x=0, int y=0, int width=0, int height=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pushes pixels outward along an expanding ring centered on a focal point\&. 
.SH "Member Function Documentation"
.PP 
.SS "void sl::Shockwave::apply (\fBBitmap\fP * source, int x = \fC0\fP, int y = \fC0\fP, int width = \fC0\fP, int height = \fC0\fP) const"
Distort a bitmap region around the configured shockwave ring\&. 
.SS "const std::string & sl::Shockwave::error () const"
Return the most recent initialization error\&. 
.SS "bool sl::Shockwave::initialise ()"
Compile the shockwave shader and prepare the effect\&. 
.SS "bool sl::Shockwave::is_valid () const"
Return whether the effect is ready to apply\&. 
.SS "void sl::Shockwave::set_centre (float x, float y)"
Set the normalized focal point; (0, 0) is top-left and (1, 1) is bottom-right\&. 
.SS "void sl::Shockwave::set_radius (float radius)"
Set the normalized distance of the expanding ring from its focal point\&. 
.SS "void sl::Shockwave::set_strength (float strength)"
Set the normalized outward displacement at the ring peak\&. 
.SS "void sl::Shockwave::set_width (float width)"
Set the normalized thickness of the distortion ring\&. 
.SS "void sl::Shockwave::shutdown ()"
Release resources owned by the effect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
