.TH "sl::StorageBuffer" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::StorageBuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStorageBuffer\fP (std::size_t sizeBytes)"
.br
.ti -1c
.RI "\fBStorageBuffer\fP (const \fBStorageBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBStorageBuffer\fP & \fBoperator=\fP (const \fBStorageBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBStorageBuffer\fP (\fBStorageBuffer\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBStorageBuffer\fP & \fBoperator=\fP (\fBStorageBuffer\fP &&other) noexcept"
.br
.ti -1c
.RI "bool \fBcreate\fP (std::size_t sizeBytes)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "std::size_t \fBsize_bytes\fP () const"
.br
.ti -1c
.RI "std::uint32_t \fBhandle\fP () const"
.br
.ti -1c
.RI "bool \fBupload\fP (const void *data, std::size_t sizeBytes, std::size_t offsetBytes=0)"
.br
.ti -1c
.RI "template<typename T > bool \fBupload\fP (const std::vector< T > &data, std::size_t offsetBytes=0)"
.br
.ti -1c
.RI "bool \fBreadback\fP (void *outData, std::size_t sizeBytes, std::size_t offsetBytes=0) const"
.br
.ti -1c
.RI "template<typename T > bool \fBreadback\fP (std::vector< T > &outData, std::size_t offsetBytes=0) const"
.br
.ti -1c
.RI "bool \fBbind\fP (unsigned int bindingIndex) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Owns a GPU Storage Buffer Object (SSBO) for compute and shader operations\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sl::StorageBuffer::StorageBuffer (std::size_t sizeBytes)\fC [explicit]\fP"
Allocate a GPU storage buffer with the requested capacity in bytes\&. 
.SS "sl::StorageBuffer::StorageBuffer (\fBStorageBuffer\fP && other)\fC [noexcept]\fP"
Transfer ownership of a GPU storage buffer\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool sl::StorageBuffer::bind (unsigned int bindingIndex) const"
Bind this storage buffer to a shader binding index (0\&.\&.N-1)\&. 
.SS "bool sl::StorageBuffer::create (std::size_t sizeBytes)"
Allocate/reallocate a GPU storage buffer of the specified size\&. 
.SS "void sl::StorageBuffer::destroy ()"
Release the GPU buffer resource\&. 
.SS "std::uint32_t sl::StorageBuffer::handle () const"
Return the backend handle\&. 
.SS "bool sl::StorageBuffer::is_valid () const"
Return whether the buffer holds a valid handle\&. 
.SS "\fBStorageBuffer\fP & sl::StorageBuffer::operator= (\fBStorageBuffer\fP && other)\fC [noexcept]\fP"
Release this buffer and take ownership of another buffer's resource\&. 
.SS "template<typename T > bool sl::StorageBuffer::readback (std::vector< T > & outData, std::size_t offsetBytes = \fC0\fP) const\fC [inline]\fP"
Read back data from the GPU storage buffer into a std::vector\&. 
.SS "bool sl::StorageBuffer::readback (void * outData, std::size_t sizeBytes, std::size_t offsetBytes = \fC0\fP) const"
Read back data from the GPU storage buffer into CPU memory\&. 
.SS "std::size_t sl::StorageBuffer::size_bytes () const"
Return the buffer size in bytes\&. 
.SS "template<typename T > bool sl::StorageBuffer::upload (const std::vector< T > & data, std::size_t offsetBytes = \fC0\fP)\fC [inline]\fP"
Upload a std::vector into the GPU storage buffer\&. 
.SS "bool sl::StorageBuffer::upload (const void * data, std::size_t sizeBytes, std::size_t offsetBytes = \fC0\fP)"
Upload data from CPU memory into the GPU storage buffer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
