.TH "sl::ShadowPoint" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::ShadowPoint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_fx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBy\fP = 0\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
A point in a 2D shadow-casting polygon\&. 
.SH "Member Data Documentation"
.PP 
.SS "float sl::ShadowPoint::x = 0\&.0f"
Horizontal screen coordinate in pixels\&. 
.SS "float sl::ShadowPoint::y = 0\&.0f"
Vertical screen coordinate in pixels\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
