.TH "sl::Vec2" 3 "simlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sl::Vec2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <physics\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBy\fP = 0\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
2D position or vector expressed in screen pixels\&. 
.SH "Member Data Documentation"
.PP 
.SS "float sl::Vec2::x = 0\&.0f"
Horizontal component in screen pixels or pixels per second\&. 
.SS "float sl::Vec2::y = 0\&.0f"
Vertical component in screen pixels or pixels per second\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for simlib from the source code\&.
